### ISSUE TITLE
Spans get mixed up

### ISSUE THREAD

**Issue by kubukoz** [kamon-io/kamon-http4s#14]
TL;DR calling an endpoint multiple times often causes the underlying spans to end up in a single trace.

Interesting parts:
- it didn't happen (for me) when no DB calls were made (but it didn't happen with the DB calls when the server was akka-http, not http4s)
- it's happening regardless of whether the effect is IO or Task

Discussion on gitter: https://gitter.im/kamon-io/Kamon?at=5af7460ee0b50c2d05b9248b

Reproduction repo & steps: https://github.com/kubukoz/kamon-repro

**Comment by kubukoz** [comment]
After a few hours of debugging, it turns out that this was most likely caused by not using a Context-aware ExecutionContext to start the Blaze server: `BlazeBuilder[F]` uses `global` by default.

**Comment by dpsoft** [comment]
please take a look :https://github.com/kamon-io/kamon-http4s/blob/master/README.md#useful-links

**Comment by kubukoz** [comment]
I actually got a working setup without providing a custom `ScheduledExecutorService`, just wrapping the ExecutionContext in something similar to `ExecutionContextAware` from https://gist.github.com/kubukoz/3e301c7a8a463ff8bdb3f89f40cef717 was enough.
