### ISSUE TITLE
Question about http4s 0.18.x support

### ISSUE THREAD

**Issue by MoAllenBellevue** [kamon-io/kamon-http4s#3]
The README says this update is "soon".  We are building a new app using 0.18.x and we would like to provide Prometheus metrics from the service.  Can you give us any idea when this update might be available?  Thanks.

**Comment by cspinetta** [comment]
@MoAllenBellevue thanks for your interest.

Right now we are working to support the new version `0.18.x`. We hope in the coming days to get a snapshot so you can start to test it in your app.

Meanwhile, you can wait for this snapshot with the support or just publish the metrics yourself from your application using the reporter [kamon-prometheus](https://github.com/kamon-io/kamon-prometheus) directly in your app.

I notify you when the snapshot is available.

**Comment by saraiva132** [comment]
@cspinetta Any update on when this plugin will support http4s 0.18.x ? If I can help in any way I would also gladly contribute. Keep up the good work

**Comment by damdev** [comment]
Hi @saraiva132 , I was making some changes on the module, just made a PR #4 where you can use the instrumentation as a Server Middleware and wrappers on your HttpClient's. The ideal way to use this is with the kamon-agent but that part it's not ready yet.
So if you wan't to try the module with the wrappers and give us some feedback, it will be great, in the spec's you can see how to use it:

https://github.com/kamon-io/kamon-http4s/pull/4/files#diff-4d79e65f0c8b6378c02b72f724f0c6e1R52

`val client = HttpClientWrapper[IO](Client.fromHttpService[IO](service))`

With the httpClient just wrap it with the HttpClientWrapper

https://github.com/kamon-io/kamon-http4s/pull/4/files#diff-21f9dd0d8ea0dc13854b99f10f406691R54

And for the server it's the same way as any http4s middleware:

```
HttpServerServiceWrapper(HttpService {
           case GET -> Root / "tracing" / "ok" =>  Ok("ok")
           case GET -> Root / "tracing" / "not-found"  => NotFound("not-found")
           case GET -> Root / "tracing" / "error"  => InternalServerError("This page will generate an error!")
         }
 ```

@ivantopo will publish an snapshot version with this PR so you can try it.

Thanks for your help!

**Comment by dpsoft** [comment]
@MoAllenBellevue @saraiva132 @damdev @cspinetta  I was making some changes on the module and  any feedback on https://github.com/kamon-io/kamon-http4s/pull/5  would be appreciated before the release!!

**Comment by dpsoft** [comment]
closed with https://github.com/kamon-io/kamon-http4s/pull/7
