### ISSUE TITLE
Release of 2.0.3

### ISSUE THREAD

**Issue by stsatlantis** [kamon-io/kamon-http4s#36]
The current documentation doesn't reflect released versions.

Is it possible to release the version 2.1.0? If not, then I can fix the documentation.

**Comment by dpsoft** [comment]
@stsatlantis if you want drop a PR whith the documentatoin fix go ahead.

**Comment by stsatlantis** [comment]
@dpsoft can you tell me what is the next release scheduled?

**Comment by dpsoft** [comment]
@stsatlantis I've just published the `2.0.3` version.

**Comment by stsatlantis** [comment]
Thank you for release
